{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "roles" : [],
               "location" : "sketches/aabningstale.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Bo Henriksen og andre",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "Åbningstale",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "roles" : [],
               "location" : "video/unipark.tex",
               "status" : "",
               "version" : "1",
               "author" : "uffefl, beyond, fluff, trauma, myth, m.fl.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "Unipark",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Offspring -- Pretty fly",
               "location" : "sange/koddetformigbaby.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "dunkel, jesus",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "Kod det for mig baby",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/arkaeologi.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "marvin",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "Arkæologi",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Aben -- Bernhard Christensen",
               "location" : "sange/oracle.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "marvin, jaydee",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "Oracle",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Frank Sinatra -- New York, New York",
               "location" : "sange/ituitu.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "sinus,peterw",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "Itu Itu",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/doeren.tex",
               "status" : "",
               "version" : "1.4 -- mærkelig, færdig?",
               "author" : "marvin",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "Dum som kun en dør",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/dogmekodning.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "beyond, slammer, trauma, fluff, uffefl, larswm, heidi, m.fl.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "Dogmekodning",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Aerosmith -- Living on the Edge",
               "location" : "sange/liggerderpaakoel.tex",
               "status" : "",
               "version" : "3 -- færdig",
               "author" : "agnete, jesus",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "Ligger der på køl",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/denstoredekansketch.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "dunkel",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "Den Store Dekansketch",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Disco tango a la carte - Tommy Tvebak",
               "location" : "sange/lektorat.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "trauma",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "DIKU mangler lektorat",
               "type" : "song",
               "revueyear" : "1999"
            }
         ],
         "order" : 1,
         "title" : "Akt 1"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "roles" : [],
               "melody" : "Svantes semilykkelige dag",
               "location" : "sange/windowsventeren.tex",
               "status" : "",
               "version" : "1 -- måske færdig",
               "author" : "Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "\\ldots{}Og om lidt\\ldots",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Den Gale Pose -- Spændt op til lir",
               "location" : "sange/bits-scorer-pir.tex",
               "status" : "",
               "version" : "2 -- næsten færdig",
               "author" : "peterw",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "Bits scorer pi'r",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/pyxelsort.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "marvin",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Pyxelsort",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/pyxler.tex",
               "status" : "",
               "version" : "3 -- helt fægrip",
               "author" : "marvin, panic, beyond, myth, uffefl, agnete, runem, andresen, guldfisk, gimse, hynne",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 15,
               "title" : "Pyxler",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Anouk -- Nobody's Wife",
               "location" : "sange/jantesulykkeligeliv.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "trauma",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 16,
               "title" : "Jantes Ulykkelige Liv",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Fame",
               "location" : "sange/quake.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "trauma, agnete",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 17,
               "title" : "Kværk",
               "type" : "song",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/noerderde.tex",
               "status" : "",
               "version" : "4 -- FOR færdig",
               "author" : "uffefl, trauma, beyond, agnete, runem, andresen, hynne, panic, fronck",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 18,
               "title" : "Nørder De?",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "We are the champions - Queen",
               "location" : "sange/wearethechampions.tex",
               "status" : "",
               "version" : "1",
               "author" : "Morten Jøhnk",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 19,
               "title" : "Det var så DIKU-revyen Part II",
               "type" : "song",
               "revueyear" : "1998"
            }
         ],
         "order" : 2,
         "title" : "Akt 2"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "roles" : [],
               "location" : "video/armageddon2.tex",
               "status" : "",
               "version" : "1",
               "author" : "beyond, fluff",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 20,
               "title" : "Armageddon II",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/eksamensdans.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "trauma",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 21,
               "title" : "Eksamensdans",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "melody" : "Video Video -- Brixx",
               "location" : "sange/videovideo.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "guldfisk",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 22,
               "title" : "Videospil Videospil",
               "type" : "video",
               "revueyear" : "1999"
            }
         ],
         "order" : 3,
         "title" : "Ekstranumre"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "roles" : [],
               "location" : "sketches/taeppenumre.tex",
               "status" : "",
               "version" : "2 -- brokker",
               "author" : "Revygruppen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 23,
               "title" : "Tæppenumre\\ldots",
               "type" : "sketch",
               "revueyear" : "1999"
            },
            {
               "roles" : [],
               "location" : "sketches/nyhederne.tex",
               "status" : "",
               "version" : "1.05 -- tæppenummer",
               "author" : "{\\tt uffefl} \\& {\\tt beyond}",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 24,
               "title" : "Nyhederne",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "roles" : [],
               "location" : "sketches/dummeste_ting.tex",
               "status" : "",
               "version" : "1.1 -- tæppenummer, ikke færdig",
               "author" : "beyond, trauma",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 25,
               "title" : "De 10 dummeste ting man kan sige\\ldots",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "roles" : [],
               "location" : "sketches/datalogenblevfar.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "uffefl og nogle andre",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 26,
               "title" : "Da Datalogen Blev Far",
               "type" : "sketch",
               "revueyear" : "1999"
            }
         ],
         "order" : 4,
         "title" : "Diverse"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1999"
}
