{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "You Can Leave Your Hat On",
               "location" : "sange/Aabningssang.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Martin Koch, Bo Arlif, Theo Engell og Thomas Gravgaard",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "Slå røven i sædet",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/dikoom.tex",
               "status" : "",
               "version" : "0.9",
               "author" : "Theo Engell-Nielsen \\& Dennis Lehd",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "DIKOOM v. 1.17.42",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "medley over Poul Kjøllers sange",
               "location" : "sange/cache.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Theo Engell-Nielsen \\& Jacob Marquard",
               "revuename" : "REVY 95",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "Poul Kjøllers greatest cache hits",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Summer Nights",
               "location" : "sange/solOgSommer.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Tore Green og Pernille Rasmussen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "Sol og sommer",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Look at me, I'm Sandra Dee",
               "location" : "sange/hvadSkalJegMedDKD.tex",
               "status" : "",
               "version" : "1.3",
               "author" : "Pernille Rasmussen \\& Tore Green",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "Hvad skal jeg med DKD?",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "There are Worse Things I could Do",
               "location" : "sange/HvadNu.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Tore Green \\& Pernille Rasmussen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "Hvad skal jeg stille op?",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Greased Lightning",
               "location" : "sange/lightning.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Martin Koch, Tore Green, Pernille Rasmussen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "Kørende kerne",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "You're the one that I want",
               "location" : "sange/DoubleSpace.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Rune Perstrup m.fl.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "Doublespace mit hjerte",
               "type" : "song",
               "revueyear" : "1995"
            }
         ],
         "order" : 1,
         "title" : "Akt 1"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "\"We Will Rock You\" af Queen",
               "location" : "sange/mmoaafd.tex",
               "status" : "",
               "version" : "0.995",
               "author" : "Martin Koch \\& Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "Musikmaskiner og audioalisering af flowcharts",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/MogensOgMogens.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Martin Koch, Lars Wive Marcussen, Agnete Jensen, Bo Kjellerup o.\\ a.\\ ",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "Mogens \\& Mogens",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Ta' på landet (``Jeg er på rekreation'')",
               "location" : "sange/progtrans.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Morten Heine (\\& Martin Koch, Peter Eidorff, Pernille Rasmussen)",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "Programtransformation",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/TimGordon.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Theo Engell-Nielsen, Dennis Lehd \\& Jørgen Elgaard Larsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "Dybt Godnat Historie",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Bølle Bob'' af Per Borgsten",
               "location" : "sange/JyrkiErEtLyn.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Arne Gl88Qenstrup \\& Theo Engel88Ql88Q-Niel88Qsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "Jyrki er et lyn",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/HuskPasswordet.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Morten Heine  Peter Harry Eidorff",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Husk Lige Password'et",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Walking by Myself'' af Rogers/Lane (kopi: Gary Moore)",
               "location" : "sange/skriverPaaSpecialet.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Bo Arlif",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 15,
               "title" : "Skriver på specialet",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/operatoersketch.tex",
               "status" : "",
               "version" : "0.9",
               "author" : "\\tt Lehd \\& Marvin",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 16,
               "title" : "Operatørsketch",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/pickup2.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "{\\tt marvin \\& lehd}. Revideret af {\\tt agnete, gimse, guldfisk \\& bobo}",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 17,
               "title" : "Pickup lines",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "In The Mood",
               "location" : "sange/afslutningsang.tex",
               "status" : "",
               "version" : "1.3",
               "author" : "Pernille Rasmussen, Agnete Jensen \\& Tore Green",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 18,
               "title" : "Dette var revyen",
               "type" : "song",
               "revueyear" : "1995"
            }
         ],
         "order" : 2,
         "title" : "Akt 2"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1995"
}
