{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/a01b_rumfortaelling.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Henrik Damborg   ",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "The Universe",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/a01_indledning.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Theo og Arne",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "EF-stunt (indledning)",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/a02_pia.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Henrik Damborg",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "{\\sc Pia}",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/a03_stop.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Peter Hary Eidorff",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "Stoppr@ovenummer",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/a04_kuk.tex",
               "status" : "",
               "version" : "1.0",
               "author" : " Theo Engell-Nielsen \\& Peter Harry Eidorf",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "Kuk i replikkerne",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/a05_barenecc.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Theo Engell-Hansen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "Rusvejledersang",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/a07_dagbog.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Null",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "Dagbog",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/a08_led-ledere.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Panic",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "Led, ledere, ledest",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/a09_stig.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Null \\& Jacob Lorentsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "Stig's sang",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/a10_reklame.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Mia Henrikson",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "Reklamesketches",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/a12_elefanter.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jacob Marquard",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "Elefantsangen",
               "type" : "sketch",
               "revueyear" : ""
            }
         ],
         "order" : 1,
         "title" : "Akt 1"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/b01_bohemian.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Mia Henriksen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "Eksamen",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/b02_dikuques.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Stephan Dahl",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "DIKU quest",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/b03_katastrofe.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Steen, Null, Harry, Henrik og Mia",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Den Værst Tænkelige Hændelse",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/b04_freja.tex",
               "status" : "",
               "version" : "2.0",
               "author" : "personer fra dette og sidste års revygrupper",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 15,
               "title" : "Vaxen Freja",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/b06_bergstein.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Henrik Damborg + div.\\ ``ukendte'' bidragydere",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 16,
               "title" : "Bergstein ",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/b08_pc.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jacob Marquard",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 17,
               "title" : "En Pc på et bord",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/b09_lokkehjul.tex",
               "status" : "",
               "version" : "2",
               "author" : "Mia og Harry",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 18,
               "title" : "Løkkehjulet",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/b11_dikuferi.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Stephan Dahl",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 19,
               "title" : "DIKU som feriem@al",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/b12_kernesang.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Null \\& Jacob L.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 20,
               "title" : "Kernesang",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/b13_muppetmaend.tex",
               "status" : "",
               "version" : "1.5",
               "author" : "Beyond \\& Panic \\& km",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 21,
               "title" : "To gamle gnavpotter",
               "type" : "sketch",
               "revueyear" : ""
            }
         ],
         "order" : 2,
         "title" : "Akt 2"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/c01_kantinesvineri.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Bo Arlif",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 22,
               "title" : "Der er svinet i kantinen",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/c02_johnny.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Bo Arlif, med rettelser fra Niels Ull",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 23,
               "title" : "Johnny ka' kode",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/c03_sommerfest.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Kristian Damm Jensen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 24,
               "title" : "Nu er der sommerfest",
               "type" : "sketch",
               "revueyear" : ""
            }
         ],
         "order" : 3,
         "title" : "Akt 3"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1993"
}
