{
   "name" : "DIKUrevy",
   "year" : "1993",
   "acts" : [
      {
         "order" : 1,
         "length" : 0,
         "materials" : [
            {
               "revueyear" : "",
               "length" : 0,
               "instructors" : [],
               "location" : "sketches/a01b_rumfortaelling.tex",
               "type" : "sketch",
               "order" : 1,
               "status" : "",
               "title" : "The Universe",
               "version" : "1.0",
               "roles" : [],
               "revuename" : "",
               "author" : "Henrik Damborg   ",
               "props" : []
            },
            {
               "revueyear" : "",
               "instructors" : [],
               "order" : 2,
               "location" : "sketches/a01_indledning.tex",
               "status" : "",
               "type" : "sketch",
               "length" : 0,
               "version" : "1.0",
               "title" : "EF-stunt (indledning)",
               "roles" : [],
               "revuename" : "",
               "author" : "Theo og Arne",
               "props" : []
            },
            {
               "order" : 3,
               "instructors" : [],
               "type" : "song",
               "location" : "sange/a02_pia.tex",
               "status" : "",
               "length" : 0,
               "revueyear" : "1993",
               "roles" : [],
               "version" : "1.0",
               "title" : "{\\sc Pia}",
               "author" : "Henrik Damborg",
               "revuename" : "DIKUrevy",
               "melody" : "???",
               "props" : []
            },
            {
               "roles" : [],
               "version" : "1.0",
               "title" : "Stoppr@ovenummer",
               "instructors" : [],
               "status" : "",
               "type" : "sketch",
               "location" : "sketches/a03_stop.tex",
               "order" : 4,
               "length" : 0,
               "revueyear" : "",
               "props" : [],
               "author" : "Peter Hary Eidorff",
               "revuename" : ""
            },
            {
               "revuename" : "",
               "author" : " Theo Engell-Nielsen \\& Peter Harry Eidorf",
               "props" : [],
               "revueyear" : "",
               "instructors" : [],
               "status" : "",
               "type" : "sketch",
               "order" : 5,
               "location" : "sketches/a04_kuk.tex",
               "length" : 0,
               "version" : "1.0",
               "title" : "Kuk i replikkerne",
               "roles" : []
            },
            {
               "melody" : "Bare Neccesities",
               "revuename" : "DIKUrevy",
               "author" : "Theo Engell-Hansen",
               "composer" : "Junglebogen",
               "props" : [],
               "revueyear" : "1993",
               "length" : 0,
               "instructors" : [],
               "status" : "",
               "location" : "sange/a05_barenecc.tex",
               "order" : 6,
               "type" : "song",
               "title" : "Rusvejledersang",
               "version" : "1.0",
               "roles" : []
            },
            {
               "props" : [],
               "author" : "Null",
               "revuename" : "",
               "roles" : [],
               "title" : "Dagbog",
               "version" : "1.0",
               "length" : 0,
               "instructors" : [],
               "order" : 7,
               "location" : "sketches/a07_dagbog.tex",
               "type" : "sketch",
               "status" : "",
               "revueyear" : ""
            },
            {
               "props" : [],
               "author" : "Panic",
               "revuename" : "",
               "roles" : [],
               "title" : "Led, ledere, ledest",
               "version" : "1.0",
               "length" : 0,
               "type" : "sketch",
               "instructors" : [],
               "status" : "",
               "order" : 8,
               "location" : "sketches/a08_led-ledere.tex",
               "revueyear" : ""
            },
            {
               "composer" : "Shubidua",
               "props" : [],
               "revuename" : "DIKUrevy",
               "melody" : "Krig og Fred",
               "author" : "Null \\& Jacob Lorentsen",
               "version" : "1.0",
               "title" : "Stig's sang",
               "roles" : [],
               "revueyear" : "1993",
               "instructors" : [],
               "type" : "song",
               "location" : "sange/a09_stig.tex",
               "status" : "",
               "order" : 9,
               "length" : 0
            },
            {
               "props" : [],
               "revuename" : "",
               "author" : "Mia Henrikson",
               "version" : "1.0",
               "title" : "Reklamesketches",
               "roles" : [],
               "revueyear" : "",
               "location" : "sketches/a10_reklame.tex",
               "instructors" : [],
               "status" : "",
               "type" : "sketch",
               "order" : 10,
               "length" : 0
            },
            {
               "composer" : "???",
               "props" : [],
               "author" : "Jacob Marquard",
               "melody" : "Jeg vil male himlen blå",
               "revuename" : "DIKUrevy",
               "roles" : [],
               "title" : "Elefantsangen",
               "version" : "1.0",
               "length" : 0,
               "instructors" : [],
               "location" : "sange/a12_elefanter.tex",
               "type" : "song",
               "order" : 11,
               "status" : "",
               "revueyear" : "1993"
            }
         ],
         "title" : "Akt 1"
      },
      {
         "title" : "Akt 2",
         "materials" : [
            {
               "length" : 0,
               "instructors" : [],
               "type" : "song",
               "status" : "",
               "location" : "sange/b01_bohemian.tex",
               "order" : 12,
               "revueyear" : "1993",
               "roles" : [],
               "title" : "Eksamen",
               "version" : "1.0",
               "author" : "Mia Henriksen",
               "melody" : "Bohemian Rhapsody",
               "revuename" : "DIKUrevy",
               "props" : [],
               "composer" : "Queen"
            },
            {
               "length" : 0,
               "location" : "sketches/b02_dikuques.tex",
               "instructors" : [],
               "type" : "sketch",
               "status" : "",
               "order" : 13,
               "revueyear" : "",
               "roles" : [],
               "title" : "DIKU quest",
               "version" : "1.0",
               "author" : "Stephan Dahl",
               "revuename" : "",
               "props" : []
            },
            {
               "props" : [],
               "author" : "Steen, Null, Harry, Henrik og Mia",
               "revuename" : "",
               "roles" : [],
               "title" : "Den Værst Tænkelige Hændelse",
               "version" : "1.0",
               "length" : 0,
               "type" : "sketch",
               "instructors" : [],
               "location" : "sketches/b03_katastrofe.tex",
               "status" : "",
               "order" : 14,
               "revueyear" : ""
            },
            {
               "roles" : [],
               "version" : "2.0",
               "title" : "Vaxen Freja",
               "instructors" : [],
               "order" : 15,
               "type" : "song",
               "location" : "sange/b04_freja.tex",
               "status" : "",
               "length" : 0,
               "revueyear" : "1993",
               "props" : [],
               "composer" : "Shu-bi-dua",
               "author" : "personer fra dette og sidste års revygrupper",
               "revuename" : "DIKUrevy",
               "melody" : "Hvalen Valborg"
            },
            {
               "instructors" : [],
               "location" : "sketches/b06_bergstein.tex",
               "type" : "sketch",
               "order" : 16,
               "status" : "",
               "length" : 0,
               "revueyear" : "",
               "roles" : [],
               "version" : "1.0",
               "title" : "Bergstein ",
               "author" : "Henrik Damborg + div.\\ ``ukendte'' bidragydere",
               "revuename" : "",
               "props" : []
            },
            {
               "composer" : "???",
               "props" : [],
               "author" : "Jacob Marquard",
               "melody" : "To lys på et bord",
               "revuename" : "DIKUrevy",
               "roles" : [],
               "title" : "En Pc på et bord",
               "version" : "1.0",
               "length" : 0,
               "instructors" : [],
               "order" : 17,
               "location" : "sange/b08_pc.tex",
               "type" : "song",
               "status" : "",
               "revueyear" : "1993"
            },
            {
               "roles" : [],
               "version" : "2",
               "title" : "Løkkehjulet",
               "instructors" : [],
               "location" : "sketches/b09_lokkehjul.tex",
               "type" : "sketch",
               "order" : 18,
               "status" : "",
               "length" : 0,
               "revueyear" : "",
               "props" : [],
               "author" : "Mia og Harry",
               "revuename" : ""
            },
            {
               "version" : "1.0",
               "title" : "DIKU som feriem@al",
               "roles" : [],
               "revueyear" : "",
               "type" : "sketch",
               "instructors" : [],
               "status" : "",
               "location" : "sketches/b11_dikuferi.tex",
               "order" : 19,
               "length" : 0,
               "props" : [],
               "revuename" : "",
               "author" : "Stephan Dahl"
            },
            {
               "author" : "Null \\& Jacob L.",
               "revuename" : "DIKUrevy",
               "melody" : "Time Warp",
               "props" : [],
               "composer" : "The Rocky Horror Picture Show",
               "location" : "sange/b12_kernesang.tex",
               "instructors" : [],
               "order" : 20,
               "type" : "song",
               "status" : "",
               "length" : 0,
               "revueyear" : "1993",
               "roles" : [],
               "version" : "1.0",
               "title" : "Kernesang"
            },
            {
               "props" : [],
               "revuename" : "",
               "author" : "Beyond \\& Panic \\& km",
               "version" : "1.5",
               "title" : "To gamle gnavpotter",
               "roles" : [],
               "revueyear" : "",
               "location" : "sketches/b13_muppetmaend.tex",
               "instructors" : [],
               "status" : "",
               "order" : 21,
               "type" : "sketch",
               "length" : 0
            }
         ],
         "length" : 0,
         "order" : 2
      },
      {
         "order" : 3,
         "length" : 0,
         "materials" : [
            {
               "author" : "Bo Arlif",
               "revuename" : "DIKUrevy",
               "melody" : "Somebodys calling my name",
               "composer" : "???",
               "props" : [],
               "instructors" : [],
               "location" : "sange/c01_kantinesvineri.tex",
               "order" : 22,
               "type" : "song",
               "status" : "",
               "length" : 0,
               "revueyear" : "1993",
               "roles" : [],
               "version" : "1.0",
               "title" : "Der er svinet i kantinen"
            },
            {
               "order" : 23,
               "instructors" : [],
               "type" : "song",
               "location" : "sange/c02_johnny.tex",
               "status" : "",
               "length" : 0,
               "revueyear" : "1993",
               "roles" : [],
               "version" : "1.0",
               "title" : "Johnny ka' kode",
               "author" : "Bo Arlif, med rettelser fra Niels Ull",
               "revuename" : "DIKUrevy",
               "melody" : "Johnny B. Goode",
               "composer" : "Chuck Berry",
               "props" : []
            },
            {
               "props" : [],
               "composer" : "Bruce Springsteen",
               "author" : "Kristian Damm Jensen",
               "melody" : "Born in the USA",
               "revuename" : "DIKUrevy",
               "roles" : [],
               "title" : "Nu er der sommerfest",
               "version" : "1.0",
               "length" : 0,
               "instructors" : [],
               "type" : "song",
               "order" : 24,
               "status" : "",
               "location" : "sange/c03_sommerfest.tex",
               "revueyear" : "1993"
            }
         ],
         "title" : "Akt 3"
      }
   ]
}
