{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "???",
               "location" : "sange/lampesangen.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "tvind",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "Lampe-sangen",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/basicViden.tex",
               "status" : "",
               "version" : "1.3",
               "author" : "Jacob, Kristoffer, Gnyf, Ole, Jørgen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "Grundlæggende datalogi: ``BASICviden''",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/enPCpaEtBord.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Jacob Marquard m.fl.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "En Pc på et bord",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/egernpatruljen.tex",
               "status" : "",
               "version" : "0.6",
               "author" : "Flere Ukendte",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "Egernpatruljen",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "fra Folk og røvere i Kardemommeby",
               "location" : "sange/dat0Revision.tex",
               "status" : "",
               "version" : "0.95",
               "author" : "Martin Koch m.fl.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "Dat0-revysion",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/maend.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Anne, Lykke og gnyf efter en idé af Bo Arlif",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "Mænd og deres søgen efter stammekulturen",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/egernpatruljenII.tex",
               "status" : "",
               "version" : "0.3",
               "author" : "Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "Egernpatruljen - del I$\\!$I",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/femtenmand.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jacob Marquard",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "Femten mand på vej til prøve\\ldots",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/dat2eksamen.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "Mundtlig eksamen i brugergrænseflader",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Bohemian Rhapsody'' af Queen",
               "location" : "sange/eksamen.tex",
               "status" : "",
               "version" : "1.95",
               "author" : "Mia Henrikson",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "Eksamen",
               "type" : "song",
               "revueyear" : ""
            }
         ],
         "order" : 1,
         "title" : "Akt 1"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/fangerne.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "Fangerne på Instituttet",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Nissedrillesangen fra ``Jul~på slottet''",
               "location" : "sange/superbrugerdrillesangen.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Jørgen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "Superbrugerdrillesangen",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/denNyLektor.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jacob Marquard",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "Den ny lektor",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "The boxer --- Simon \\& Garfunkel",
               "location" : "sange/kernesang.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Kernesangen",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/egernpatruljenIII.tex",
               "status" : "",
               "version" : "0.96",
               "author" : "Jørgen Elgaard Larsen og tvind",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 15,
               "title" : "Kantinevagten $\\sqrt2$ / TV-kantinen",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Rabalderstræde",
               "location" : "sange/herPaaStedet.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "tvind",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 16,
               "title" : "Her på stedet\\ldots",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/evaluering.tex",
               "status" : "",
               "version" : "0.9",
               "author" : "Harry",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 17,
               "title" : "Revyloering",
               "type" : "sketch",
               "revueyear" : ""
            }
         ],
         "order" : 2,
         "title" : "Akt 2"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1994"
}
