{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/konferencier.tex",
               "status" : "",
               "version" : "0.5",
               "author" : "Jacob",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "Konferenciernummer",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Alt det som ingen ser",
               "location" : "sange/revyeningenser.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "?",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "Revyen, som ingen ser",
               "type" : "song",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/julemand.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Morten et.\\ al.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "Julemand",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/dat0hul.tex",
               "status" : "",
               "version" : "0.9",
               "author" : "Rachid",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "Dat 0 er et hul",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/rekrutte.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "PJo (credit Monthy Python)",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "Rekrutteringsproblemer",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "The Eagles: Hotel California",
               "location" : "sange/VelkommenTilDIKU.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Henrik \\& Mia",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "Velkommen til 1.\\ del p\\aa\\ {\\sc diku}",
               "type" : "song",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "I'm a Lumberjack",
               "location" : "sange/Datalog.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jacob",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "Jeg er datalog",
               "type" : "song",
               "composer" : "Monty Python",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/doven.tex",
               "status" : "",
               "version" : "0.9",
               "author" : "Jacob",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "Doven evaluering",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/neural.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Allan og Gnyf, id\\'e: NULL",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "Neurale netværk",
               "type" : "sketch",
               "revueyear" : "1992"
            }
         ],
         "order" : 1,
         "title" : "Akt 1"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Shubidua: Tryk på",
               "location" : "sange/trykpaa.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "NULL, Ole",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "News på",
               "type" : "song",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/basicviden.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jacob, Kristoffer, Gnyf, Ole",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "Grundlæggende datalogi: ``BASICviden''",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Dyrene i Hakkebakkeskoven: Peberkagebagesangen",
               "location" : "sange/DIKUgryde.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Henrik og Mia (= Ida og Bent From)",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "DIKUGRYDE-SANGEN",
               "type" : "song",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/examrepe.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Jake + Monty Python",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "Eksamens Repetion",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "John Mogensen: Så længe jeg lever",
               "location" : "sange/salangejeglaeser.tex",
               "status" : "",
               "version" : "2.0",
               "author" : "Niels Ull Jacobsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Så længe jeg læser",
               "type" : "song",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/selvref.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Morten",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 15,
               "title" : "Selvreference",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "En eller anden franskmand",
               "location" : "sange/sigdeord.tex",
               "status" : "",
               "version" : "0.9",
               "author" : "PH -- og lidt Morten",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 16,
               "title" : "Sig de ord du ved....",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/nynne.tex",
               "status" : "",
               "version" : "2.0",
               "author" : "Kristoffer, Henrik og Mia",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 17,
               "title" : "NYNNE",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/penge.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Kristoffer",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 18,
               "title" : "Penge, Penge!",
               "type" : "sketch",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Shubidua: Sexchikane",
               "location" : "sange/sexchika.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Kristoffer",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 19,
               "title" : "Sexchikane",
               "type" : "song",
               "revueyear" : "1992"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sange/afslut.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jacob",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 20,
               "title" : "Afslutningssang",
               "type" : "sketch",
               "revueyear" : "1992"
            }
         ],
         "order" : 2,
         "title" : "Akt 2"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Du må få min sofacykel",
               "location" : "sange/lemminger.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Gnyf og Lykke",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 21,
               "title" : "Åh, det lemmingspil...",
               "type" : "song",
               "revueyear" : "1992"
            }
         ],
         "order" : 3,
         "title" : "Ekstranumre"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1992"
}
