{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/1-01-Indledning.tex",
               "status" : "",
               "version" : "0.0",
               "author" : "Revyboss",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "Indledning, rygeforbud, mm.",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/1-02-Intro.tex",
               "status" : "",
               "version" : "0.9b",
               "author" : "Theo og Uffe",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "Intro 3",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Arh der -- MC Einar",
               "location" : "sange/1-03-Aabningssang.tex",
               "status" : "",
               "version" : "0.85",
               "author" : "Tore Green, Pernille Rasmussen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "Åbningssang",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/1-04-90aarsKernen.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Uffe, Søren, Rasmus S., Lars",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "90 års 1M revisionen",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/1-05-RHPSKlister.tex",
               "status" : "",
               "version" : "1.05",
               "author" : "Rune Perstrup",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "Klister til Rocky Horror Picture Show",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Science Fiction - double feature",
               "location" : "sange/1-06-VoresHistorieStarter.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Rune Perstrup",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "Vores Historie Starter",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Let's do the time warp again",
               "location" : "sange/1-07-SaaKoererEmbla.tex",
               "status" : "",
               "version" : "1.11",
               "author" : "Rune Perstrup",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "Så kører Embla igen",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Sweet Transvestite",
               "location" : "sange/1-08-JegErOperatoeren.tex",
               "status" : "",
               "version" : "1.11",
               "author" : "Rune Perstrup",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "Jeg er operatøren",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "I can make you a man",
               "location" : "sange/1-09-JegKanGoerHamTilMand.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Rune Perstrup",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "Jeg kan gør dig til mand!!",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Touch Me",
               "location" : "sange/1-10-TagMig.tex",
               "status" : "",
               "version" : "1.11",
               "author" : "Rune Perstrup",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "Ta' mig!",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Whatever happened to saturday night",
               "location" : "sange/1-11-SoerenOlsen.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Rune Perstrup",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "Søren Olsens Sang",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/1-12-LANsTale.tex",
               "status" : "",
               "version" : "0.95",
               "author" : "Søren TM",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "LANs tale til nationen",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Fredagssangen med Tæskeholdet",
               "location" : "sange/1-13-FredagsSangen.tex",
               "status" : "",
               "version" : "0.91",
               "author" : "Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "Fredagssangen",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/1-14-FysikKlister.tex",
               "status" : "",
               "version" : "0.1",
               "author" : "Revygruppen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Fysikklister",
               "type" : "sketch",
               "revueyear" : "1997"
            }
         ],
         "order" : 1,
         "title" : "Akt 1"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/2-01-FysikSketch.tex",
               "status" : "",
               "version" : "--0.1",
               "author" : "Theo, Søren, Peter, Rune, \\ldots",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 15,
               "title" : "Fysiksketch",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Norse Black Metal---Red Warszawa",
               "location" : "sange/2-02-StandardML.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Jesper Holm Olsen, Martin Koch, Pia D.\\ J.\\ ",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 16,
               "title" : "Standard ML - og Mads",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/2-03-AllesKonto.tex",
               "status" : "",
               "version" : "0.9b",
               "author" : "Uffe Friis Lichtenberg og Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 17,
               "title" : "Alles konto er blevet lukket",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Jeg har købt en guitar - Shubiduhaba",
               "location" : "sange/2-04-JegHarGlemtMitPassword.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Jesper Holm Olsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 18,
               "title" : "Jeg har glemt mit password",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/2-05-Pipeline.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Søren Trautner Madsen \\& Jesper H.\\ Olsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 19,
               "title" : "Pipelinesketch",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Come on Eileen - Dexy's Midnight Runners",
               "location" : "sange/2-06-Eileen.tex",
               "status" : "",
               "version" : "0.93",
               "author" : "Theo Engell-Nielsen \\& Stefanovitz Trautner Muhatma",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 20,
               "title" : "Kom nu Eileen",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/2-07-OndMonolog.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Søren Trautner Madsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 21,
               "title" : "Ond monolog",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/2-08-IkkeVoresCola.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Skrevet af Ida Gimsing, Katrine Hommelhof, Jonas Ussing, Lars WM",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 22,
               "title" : "Ikke vores Cola",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Don't Cry for Me Argentina - Andrew Lloyd \\emph{Webber}",
               "location" : "sange/2-09-DetVarSaaDIKURevyen.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Theo Engell-Nielsen \\& Peter Harry Eidorff",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 23,
               "title" : "Det var så \\sc{DIKU}-Revyen",
               "type" : "song",
               "revueyear" : "1997"
            }
         ],
         "order" : 2,
         "title" : "Akt 2"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Bananer, Bananer'' af Onkel Dum og Bananerne",
               "location" : "sange/3-01-JavaJava.tex",
               "status" : "",
               "version" : "1.",
               "author" : "Theo Engell \\& Katrine Hommelhoff Jensen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 24,
               "title" : "Java Java, jeg kan ikke få nok",
               "type" : "song",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Irene mudder",
               "location" : "sange/3-02-SirenenTuder.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Søren T. Martin K.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 25,
               "title" : "Sirenen Tuder",
               "type" : "song",
               "revueyear" : "1997"
            }
         ],
         "order" : 3,
         "title" : "Ekstranumre"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1997"
}
