{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/aabningstale.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "Rasmus (\\texttt{rmoller})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "Præsentation",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/intro.tex",
               "status" : "",
               "version" : "0.9 -- ikke helt faerdig",
               "author" : "",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "Intro 4: Nemesis",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/noerder.tex",
               "status" : "",
               "version" : "3.6 -- færdig",
               "author" : "Henning Makholm, Søren Madsen, Theo Engell, m.fl.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "Nørdkammerater",
               "type" : "sketch",
               "revueyear" : "1997"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/m_klister.tex",
               "status" : "",
               "version" : "2.1 -- færdig",
               "author" : "Rune (\\texttt{guldfisk})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "M: Musical Klister",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Backstreet's Back -- Backstreet Boys",
               "location" : "sange/m_backstreetsback.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "Rune (\\texttt{guldfisk})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "M: Backstreet's Back",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Europe -- The Final Countdown",
               "location" : "sange/finalcountdown.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "Søren (\\texttt{trauma})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "M: The Final Countdown",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Back for good -- Take that",
               "location" : "sange/m_backforgood.tex",
               "status" : "",
               "version" : "2 -- helt færdig",
               "author" : "Rune (\\texttt{guldfisk}) kortekst: Søren Takethatner MadZone",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "M: Back for good",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "We've got it going on -- hvem?",
               "location" : "sange/m_wevegotitgoingon.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "Rune (\\texttt{guldfisk})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "M: We've got it going on",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/taeppe_42.tex",
               "status" : "",
               "version" : "0.4",
               "author" : "Revygruppen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "42",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/nyrup.tex",
               "status" : "",
               "version" : "0.9 -- færdig",
               "author" : "lyst, men ej blåt til lyst (don't \\textsf{panic})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "Nyrup's got IT",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/taeppe_netscape.tex",
               "status" : "",
               "version" : "0.4",
               "author" : "Revygruppen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "Netscape",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "(DataloBee Gees -- Stayin' Alive)",
               "location" : "sange/dh_koderlidt.tex",
               "status" : "",
               "version" : "1.1 -- helt færdig",
               "author" : "Søren (\\texttt{trauma})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "Koder lidt",
               "type" : "song",
               "revueyear" : "1998"
            }
         ],
         "order" : 1,
         "title" : "Akt 1"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Østkyst Hustlers -- Han får for lidt",
               "location" : "sange/hankoderslam.tex",
               "status" : "",
               "version" : "5 -- færdig",
               "author" : "Uffe (\\texttt{uffefl}), Martin (\\texttt{myth}) og Jesper (\\texttt{dunkel})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "Han koder slam",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/melbrooks.tex",
               "status" : "",
               "version" : "2.1 -- færdig",
               "author" : "Jonas (\\texttt{duck}), Uffe (\\texttt{uffefl}), m.fl.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Højt at kode",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/taeppe_edbafdelingen.tex",
               "status" : "",
               "version" : "0.4",
               "author" : "Revygruppen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 15,
               "title" : "EDB-afdelingen",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "For kendt -- Lex \\& Klatten",
               "location" : "sange/jegerfordum.tex",
               "status" : "",
               "version" : "1.0 -- færdig",
               "author" : "Theo Engell",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 16,
               "title" : "For dum til det her sted...",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/vektorborge.tex",
               "status" : "",
               "version" : "1 -- næsten færdig",
               "author" : "Uffe (\\texttt{uffefl}) et. al.",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 17,
               "title" : "Vektor Borge",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/taeppe_darthvader.tex",
               "status" : "",
               "version" : "0.4",
               "author" : "Revygruppen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 18,
               "title" : "Tæppenumre\\ldots",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/densvenskekoder.tex",
               "status" : "",
               "version" : "1.0",
               "author" : "Sidsel, Bobo, Duck, Uphfe",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 19,
               "title" : "Den Svenske Koder",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/denstoreinstruktor_1.tex",
               "status" : "",
               "version" : "1.1 -- færdig",
               "author" : "Theo (\\texttt{beyond}) og Søren (\\texttt{trauma}) -- det er deres skuld det hele",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 20,
               "title" : "Den store Instruktorsketch 1",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Land of confusion -- Genesis",
               "location" : "sange/landofconfusion.tex",
               "status" : "",
               "version" : "1.0 -- færdig",
               "author" : "Søren$^\\textrm{\\small TM}$, Martin Koch",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 21,
               "title" : "I DAG er verden vor",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/denstoreinstruktor_2.tex",
               "status" : "",
               "version" : "1.1 -- færdig",
               "author" : "Theo (\\texttt{beyond}) og Søren (\\texttt{trauma}) -- det er deres skuld det hele",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 22,
               "title" : "Den store Instruktorsketch 2",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/psykolog.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "Maren Sødsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 23,
               "title" : "Psykologhjælp",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/denstoreinstruktor_3.tex",
               "status" : "",
               "version" : "1.1 -- færdig",
               "author" : "Theo (\\texttt{beyond}) og Søren (\\texttt{trauma}) -- det er deres skuld det hele",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 24,
               "title" : "Den store Instruktorsketch 3",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/emailfraloenneberg.tex",
               "status" : "",
               "version" : "2 -- færdig",
               "author" : "Rune (\\texttt{guldfisk}) \\& Arne ($\\neg$\\texttt{guldfisk})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 25,
               "title" : "Dybt Godnat part II: E-mail fra L\\\"onneberg",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/taeppe_hukommelsestab.tex",
               "status" : "",
               "version" : "0.4",
               "author" : "Revygruppen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 26,
               "title" : "Tæppenumre\\ldots",
               "type" : "sketch",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Leave me alone -- Michael Jackson",
               "location" : "sange/leavemealone.tex",
               "status" : "",
               "version" : "1 -- næsten færdig",
               "author" : "Theo (\\texttt{beyond})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 27,
               "title" : "Leave me alone",
               "type" : "song",
               "revueyear" : "1998"
            }
         ],
         "order" : 2,
         "title" : "Akt 2"
      },
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Beethovens 5. Skæbnesymfonien",
               "location" : "sange/datalogidatalogi.tex",
               "status" : "",
               "version" : "1 -- færdig",
               "author" : "Søren (\\texttt{trauma})",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 28,
               "title" : "Datalogi!",
               "type" : "song",
               "revueyear" : "1998"
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "Tubthumping -- Chumbawamba",
               "location" : "sange/revynerslut.tex",
               "status" : "",
               "version" : "1.0 -- færdig",
               "author" : "Theo Engell \\& Søren Trautner",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 29,
               "title" : "Revy'n er slut!",
               "type" : "song",
               "revueyear" : "1998"
            }
         ],
         "order" : 3,
         "title" : "Ekstranumre"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1998"
}
