{
   "acts" : [
      {
         "length" : 0,
         "materials" : [
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/ny_aabningssketch.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 1,
               "title" : "Revyen i revyen",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``You oughta know'' -- Alanis Morisette",
               "location" : "sange/aabningssang.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Theo Engell-Nielsen \\& Peter Harry Eidorff",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 2,
               "title" : "Der er DIKU-REVY!",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/infpsyk.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Theo Engell",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 3,
               "title" : "Informationspsykologen",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/klister_brokker.tex",
               "status" : "",
               "version" : "2.05",
               "author" : "Theo Engell-Nielsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 4,
               "title" : "Bar røv, nøgler og studiekort",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/lifeofdiku.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Peter W. Nielsen, Jesper Holm Olsen og Søren Trautner Madsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 5,
               "title" : "Life of DIKU",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Sårhus'' -- Shubidua",
               "location" : "sange/1m-sang.tex",
               "status" : "",
               "version" : "1.25",
               "author" : "Søren Trautner Madsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 6,
               "title" : "Censormanden",
               "type" : "song",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Diggin' on James Brown'' -- Tower of Power",
               "location" : "sange/ML.tex",
               "status" : "",
               "version" : "1.101",
               "author" : "Tore Green",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 7,
               "title" : "Det' meget pæner' i ML",
               "type" : "song",
               "revueyear" : "1996"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/taeppenumre.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Diverse",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 8,
               "title" : "Tæppenumre",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Enter Sandman'' -- Metallica",
               "location" : "sange/eksamensdag.tex",
               "status" : "",
               "version" : "1.101",
               "author" : "Søren Trautner Madsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 9,
               "title" : "Eksamensdag",
               "type" : "song",
               "revueyear" : "1996"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/ny_natiHEL.tex",
               "status" : "",
               "version" : "0.910031",
               "author" : "Hslowhand, kokdg, trauma \\& marvin",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 10,
               "title" : "Forårsklassikeren",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "melody" : "``Live'n let die'' -- Paul Mcartney",
               "location" : "sange/leverpostej.tex",
               "status" : "",
               "version" : "1.101",
               "author" : "Søren Trautner Madsen",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 11,
               "title" : "Leverpostej",
               "type" : "song",
               "revueyear" : "1995"
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/atomkrig.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "\\tt{trauma}, \\tt{beyond}, \\tt{marvin}",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 12,
               "title" : "Atomkrig 1996",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/colaopfyldning.tex",
               "status" : "",
               "version" : "1.2",
               "author" : "Revygruppen, indskrevet af \\tt{beyond}",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 13,
               "title" : "Cola i slowmotion",
               "type" : "sketch",
               "revueyear" : ""
            },
            {
               "instructors" : [],
               "roles" : [],
               "location" : "sketches/datarobics.tex",
               "status" : "",
               "version" : "1.1",
               "author" : "Theo Engell-Nielsen, Søren Trautner Madsen + mange andre",
               "revuename" : "",
               "length" : 0,
               "props" : [],
               "order" : 14,
               "title" : "Datarobics",
               "type" : "sketch",
               "revueyear" : ""
            }
         ],
         "order" : 1,
         "title" : "Et akt"
      }
   ],
   "name" : "DIKUrevy",
   "year" : "1996"
}
